---
deployment:
      tasks:
        - export DEPLOYPATH=/home/siqwbxlw/xchange.siqware.com/  # Add /<app_folder> if required
        #- /bin/cp pks-database.sql $DEPLOYPATH                 #Copy specific file to destination from root
        #- /bin/cp /<sub_folder>/<file_name> $DEPLOYPATH   #copy specific file from source sub folder
        #- /bin cp * $DEPLOYPATH                           #copy all from root 
        #- /bin cp /<sub_folder>/* $DEPLOYPATH             #copy all from sub folder root
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        
